 # Индивидуальное $№1$.

### Вариант $№3$.

### Дана целочисленная прямоугольная матрица. Определить:
### количество столбцов, содержащих хотя бы один нулевой элемент;
### номер строки, в которой находится самая длинная серия одинаковых элементов.

In [28]:
import numpy as np # импортируем нужную библиотеку

### Задаём размеры матрицы и создаём её, используя метод random.

In [29]:
num_rows = 4
num_columns = 5

matrix = np.random.randint(low=0, high=10, size=(num_rows, num_columns))
print("Исходная матрица:")
print(matrix)

Исходная матрица:
[[2 8 8 8 4]
 [4 1 3 4 2]
 [1 0 7 8 9]
 [1 4 7 9 5]]


### Находим номер строки, в которой есть хотя бы один нулевой элемент.

In [30]:
num_columns_with_zeros = np.sum(np.any(matrix == 0, axis=0))
print("Количество столбцов с нулевыми элементами:", num_columns_with_zeros)

Количество столбцов с нулевыми элементами: 1


### Находим номер строки с самой длинной серией одинаковых элементов.

In [31]:
diff_matrix = np.diff(matrix, axis=1)
row_with_longest_series = np.argmax(np.max(np.diff(np.where(diff_matrix != 0), axis=1), axis=1))
print("Номер строки с самой длинной серией одинаковых элементов:", row_with_longest_series)

Номер строки с самой длинной серией одинаковых элементов: 1
